name: Run static checks

on:
    push:
      branches:
        - "master"
    pull_request:
      branches:
        - "master"
    release:
        types:
            - published
            - prereleased

jobs:

    run_test_case:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                builder:
                  - "5.5-2:1.18.3-27.2-3-ubuntu24.04"

        container: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}"

        steps:
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            submodules: recursive
        - name: work around https://github.com/actions/checkout/issues/766
          run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        - name: Run tests
          run: |
            set -e
            make xref
            make dialyzer
